spring:
  datasource:    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/client
    username: postgres
    password: postgre 
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:      ddl-auto: update
        